package reviser

import (
	"go/ast"
	"go/token"
	"regexp"
)

const (
	StandardInput        = "<standard-input>"
	stringValueSeparator = ","
)

var (
	codeGeneratedPattern = regexp.MustCompile(`^// Code generated .* DO NOT EDIT\.$`)
)

// SourceFile main struct for fixing an existing code
type SourceFile struct {
	shouldRemoveUnusedImports      bool
	shouldUseAliasForVersionSuffix bool
	shouldFormatCode               bool
	shouldSkipAutoGenerated        bool
	shouldSeparateNamedImports     bool
	hasSeparateSideEffectGroup     bool
	companyPackagePrefixes         []string
	importsOrders                  ImportsOrders

	projectName string
	filePath    string
}

// NewSourceFile constructor
func NewSourceFile(projectName, filePath string) *SourceFile { _ = "STUB: not implemented"; return nil }

// Fix is for revise imports and format the code. Returns formated content, original content, true if formatted content is different from original and error.
func (f *SourceFile) Fix(options ...SourceFileOption) ([]byte, []byte, bool, error) {
	_ = "STUB: not implemented"
	return nil, nil, false, nil
}

func isFileAutoGenerate(pf *ast.File) bool { _ = "STUB: not implemented"; return false }

func (f *SourceFile) formatDecls(file *ast.File) { _ = "STUB: not implemented"; return }

func fixCommentGroup(commentGroup *ast.CommentGroup) *ast.CommentGroup {
	_ = "STUB: not implemented"
	return nil
}

func (f *SourceFile) groupImports(
	projectName string,
	localPkgPrefixes []string,
	importsWithMetadata map[string]*commentsMetadata,
) *groupsImports {
	_ = "STUB: not implemented"
	return nil
}

func skipPackageAlias(pkg string) string { _ = "STUB: not implemented"; return "" }

func generateFile(fset *token.FileSet, f *ast.File) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func isSingleCgoImport(dd *ast.GenDecl) bool { _ = "STUB: not implemented"; return false }

func (f *SourceFile) fixImports(
	file *ast.File,
	groups *groupsImports,
	commentsMetadata map[string]*commentsMetadata,
) {
	_ = "STUB: not implemented"
	return
}

// hasMultipleImportDecls will return combined import declarations to single declaration
//
// Ex.:
// import "fmt"
// import "io"
// -----
// to
// -----
// import (
//
//	"fmt"
//	"io"
//
// )
func hasMultipleImportDecls(f *ast.File) ([]ast.Decl, bool) {
	_ = "STUB: not implemented"
	return nil, false
}

func removeEmptyImportNode(f *ast.File) { _ = "STUB: not implemented"; return }

func rebuildImports(tok token.Token, commentsMetadata map[string]*commentsMetadata, imports [][]string) []ast.Spec {
	_ = "STUB: not implemented"
	return nil
}

func clearImportDocs(f *ast.File, importsPositions []*importPosition) {
	_ = "STUB: not implemented"
	return
}

func importWithComment(imprt string, commentsMetadata map[string]*commentsMetadata) string {
	_ = "STUB: not implemented"
	return ""
}

func (f *SourceFile) parseImports(file *ast.File) (map[string]*commentsMetadata, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Retry without build tag — files with custom build constraints
// (like tools.go with //+build tools) may cause go list conflicts
// when the file imports the project itself.

func setAliasForVersionedImportSpec(importSpec *ast.ImportSpec, packageImports map[string]string) string {
	_ = "STUB: not implemented"
	return ""
}

type commentsMetadata struct {
	Doc     *ast.CommentGroup
	Comment *ast.CommentGroup
}

type importPosition struct {
	Start token.Pos
	End   token.Pos
}

func (p *importPosition) IsInRange(comment *ast.CommentGroup) bool {
	_ = "STUB: not implemented"
	return false
}
